// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihcqxgszsodvexfedvdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloY3F4Z3N6c29kdmV4ZmVkdmR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTU4NTUsImV4cCI6MjA2NTk5MTg1NX0.1v3ute6aumJmMSvqycn5S3V4iCm7YTJ3xSTH4yK0aNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);